title: YAML Config Demo
description: A demo of rendering YAML data with Jekyll
baseurl: ""
url: ""
markdown: kramdown

# Collections
collections:
  products:
    output: true
    permalink: /products/:path/
